/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// Error struct for Error
type Error struct {
	Code int32 `json:"code"`
	Message string `json:"message"`
}
