/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// TweetLookupResponseMeta struct for TweetLookupResponseMeta
type TweetLookupResponseMeta struct {
	// The next cursor provided by the response.
	NextToken string `json:"next_token,omitempty"`
	// The ID of the oldest Tweet in the response.
	OldestId string `json:"oldest_id,omitempty"`
	// The ID of the newest Tweet in the response.
	NewestId string `json:"newest_id,omitempty"`
	// The previous cursor provided by the response.
	PreviousToken string `json:"previous_token,omitempty"`
	// Number of results returned in the response.
	ResultCount int32 `json:"result_count,omitempty"`
}
