/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// Rule struct for Rule
type Rule struct {
	// The filterlang value of the rule.
	Value string `json:"value"`
	// A tag meant for the labeling of user provided rules.
	Tag string `json:"tag,omitempty"`
	// Unique identifier of this rule.
	Id string `json:"id,omitempty"`
}
