/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// OperationalDisconnectProblem You have been disconnected for operational reasons.
type OperationalDisconnectProblem struct {
	Title string `json:"title"`
	Detail string `json:"detail"`
	Type string `json:"type,omitempty"`
	DisconnectType string `json:"disconnect_type,omitempty"`
}
