/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// RuleDeleteIds struct for RuleDeleteIds
type RuleDeleteIds struct {
	// The filterlang value of the rule.
	Ids []string `json:"ids"`
}
