/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// TweetGeo The location tagged on the Tweet, if the user provided one.
type TweetGeo struct {
	Coordinates Point `json:"coordinates,omitempty"`
	// The identifier for this place
	PlaceId string `json:"place_id,omitempty"`
}
