/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// InvalidRequestProblemAllOfErrors struct for InvalidRequestProblemAllOfErrors
type InvalidRequestProblemAllOfErrors struct {
	Parameters map[string][]string `json:"parameters,omitempty"`
	Message string `json:"message,omitempty"`
}
