/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// UnsupportedAuthenticationProblemAllOf struct for UnsupportedAuthenticationProblemAllOf
type UnsupportedAuthenticationProblemAllOf struct {
	Type string `json:"type,omitempty"`
}
