/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// ContextAnnotationDomainFields Represents the data for the context annotation domain.
type ContextAnnotationDomainFields struct {
	// The unique id for a context annotation domain.
	Id string `json:"id"`
	// Name of the context annotation domain.
	Name string `json:"name,omitempty"`
	// Description of the context annotation domain.
	Description string `json:"description,omitempty"`
}
