/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// ConnectionExceptionProblem A problem that indicates something is wrong with the connection
type ConnectionExceptionProblem struct {
	Title string `json:"title"`
	Detail string `json:"detail"`
	Type string `json:"type,omitempty"`
	ConnectionIssue string `json:"connection_issue,omitempty"`
}
