/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// ResourceUnauthorizedProblemAllOf struct for ResourceUnauthorizedProblemAllOf
type ResourceUnauthorizedProblemAllOf struct {
	Type string `json:"type,omitempty"`
	Value string `json:"value"`
	Parameter string `json:"parameter"`
	Section string `json:"section"`
	ResourceType string `json:"resource_type"`
}
