/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// InlineResponse200Data struct for InlineResponse200Data
type InlineResponse200Data struct {
	Hidden bool `json:"hidden,omitempty"`
}
