/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// ProblemFields struct for ProblemFields
type ProblemFields struct {
	Title string `json:"title"`
	Detail string `json:"detail"`
}
