/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// PhotoAllOf struct for PhotoAllOf
type PhotoAllOf struct {
	Type string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}
