/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
import (
	"time"
)
// Tweet struct for Tweet
type Tweet struct {
	// Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
	Id string `json:"id"`
	// Creation time of the Tweet.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The content of the Tweet.
	Text string `json:"text"`
	// Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
	AuthorId string `json:"author_id,omitempty"`
	// Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
	InReplyToUserId string `json:"in_reply_to_user_id,omitempty"`
	// Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
	ConversationId string `json:"conversation_id,omitempty"`
// not implemented yet	ConversationControl ConversationControl `json:"conversation_control,omitempty"`
	// A list of Tweets this Tweet refers to. For example, if the parent Tweet is a Retweet, a Quoted Tweet or a Reply, it will include the related Tweet referenced to by its parent.
	ReferencedTweets []TweetReferencedTweets `json:"referenced_tweets,omitempty"`
	Attachments TweetAttachments `json:"attachments,omitempty"`
	ContextAnnotations []ContextAnnotation `json:"context_annotations,omitempty"`
	Withheld TweetWithheld `json:"withheld,omitempty"`
	Geo TweetGeo `json:"geo,omitempty"`
	Entities FullTextEntities `json:"entities,omitempty"`
	PublicMetrics TweetPublicMetrics `json:"public_metrics,omitempty"`
	// Indicates if this Tweet contains URLs marked as sensitive, for example content suitable for mature audiences.
	PossiblySensitive bool `json:"possibly_sensitive,omitempty"`
	// Language of the Tweet, if detected by Twitter. Returned as a BCP47 language tag.
	Lang string `json:"lang,omitempty"`
	// The name of the app the user Tweeted from.
	Source string `json:"source,omitempty"`
	NonPublicMetrics TweetNonPublicMetrics `json:"non_public_metrics,omitempty"`
	PromotedMetrics TweetPromotedMetrics `json:"promoted_metrics,omitempty"`
	OrganicMetrics TweetOrganicMetrics `json:"organic_metrics,omitempty"`
}
