/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// CommonMediaFields struct for CommonMediaFields
type CommonMediaFields struct {
	// The Media Key identifier for this attachment.
	MediaKey string `json:"media_key,omitempty"`
	// The height of the media in pixels
	Height int32 `json:"height,omitempty"`
	// The width of the media in pixels
	Width int32 `json:"width,omitempty"`
}
