/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// OperationalDisconnectProblemAllOf struct for OperationalDisconnectProblemAllOf
type OperationalDisconnectProblemAllOf struct {
	Type string `json:"type,omitempty"`
	DisconnectType string `json:"disconnect_type,omitempty"`
}
