/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// UserLookupResponse struct for UserLookupResponse
type UserLookupResponse struct {
	Data []User `json:"data,omitempty"`
	Includes Expansions `json:"includes,omitempty"`
	Errors []Problem `json:"errors,omitempty"`
}
