/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// Expansions struct for Expansions
type Expansions struct {
	Users []User `json:"users,omitempty"`
	Tweets []Tweet `json:"tweets,omitempty"`
	Places []Place `json:"places,omitempty"`
	Media []Media `json:"media,omitempty"`
	Polls []Poll `json:"polls,omitempty"`
}
