/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// InlineResponse2001Meta struct for InlineResponse2001Meta
type InlineResponse2001Meta struct {
	// Most recent Tweet Id returned by search query
	NewestId string `json:"newest_id,omitempty"`
	// Oldest Tweet Id returned by search query
	OldestId string `json:"oldest_id,omitempty"`
	// This value is used to get the next 'page' of results by providing it to the next_token parameter.
	NextToken string `json:"next_token,omitempty"`
	// Number of search query results
	ResultCount int32 `json:"result_count,omitempty"`
}
