/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// FieldUnauthorizedProblemAllOf struct for FieldUnauthorizedProblemAllOf
type FieldUnauthorizedProblemAllOf struct {
	Type string `json:"type,omitempty"`
	Section string `json:"section"`
	ResourceType string `json:"resource_type"`
	Field string `json:"field"`
}
