/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// ResourceNotFoundProblemAllOf struct for ResourceNotFoundProblemAllOf
type ResourceNotFoundProblemAllOf struct {
	Type string `json:"type,omitempty"`
	Parameter string `json:"parameter"`
	// Value will match the schema of the field.
	Value interface{} `json:"value"`
	ResourceType string `json:"resource_type"`
}
