/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// RulesResponseMetadata struct for RulesResponseMetadata
type RulesResponseMetadata struct {
	Sent string `json:"sent"`
	Summary RulesRequestSummary `json:"summary,omitempty"`
}
