/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// UserWithheld Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
type UserWithheld struct {
	// Provides a list of countries where this content is not available.
	CountryCodes []string `json:"country_codes"`
	// Indicates that the content being withheld is a `user`.
	Scope string `json:"scope,omitempty"`
}
