/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// AddRulesRequest struct for AddRulesRequest
type AddRulesRequest struct {
	Add []RuleNoId `json:"add"`
}
