/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
import (
	"time"
)
// Poll Represent a Poll attached to a Tweet
type Poll struct {
	// Unique identifier of this poll.
	Id string `json:"id"`
	Options []PollOption `json:"options"`
	VotingStatus string `json:"voting_status,omitempty"`
	EndDatetime time.Time `json:"end_datetime,omitempty"`
	DurationMinutes int32 `json:"duration_minutes,omitempty"`
}
