/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// UsageCapExceededProblemAllOf struct for UsageCapExceededProblemAllOf
type UsageCapExceededProblemAllOf struct {
	Type string `json:"type,omitempty"`
	Period string `json:"period,omitempty"`
	Scope string `json:"scope,omitempty"`
}
