/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// UsageCapExceededProblem A problem that indicates that a usage cap has been exceeded.
type UsageCapExceededProblem struct {
	Title string `json:"title"`
	Detail string `json:"detail"`
	Type string `json:"type,omitempty"`
	Period string `json:"period,omitempty"`
	Scope string `json:"scope,omitempty"`
}
