/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// DeleteRulesResponse struct for DeleteRulesResponse
type DeleteRulesResponse struct {
	Meta RulesResponseMetadata `json:"meta"`
}
