/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// ClientForbiddenProblem A problem that indicates your client is forbidden from making this request.
type ClientForbiddenProblem struct {
	Title string `json:"title"`
	Detail string `json:"detail"`
	Type string `json:"type,omitempty"`
	Reason string `json:"reason,omitempty"`
	RegistrationUrl string `json:"registration_url,omitempty"`
}
