/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// PlaceType the model 'PlaceType'
type PlaceType string

// List of PlaceType
const (
	POI PlaceType = "poi"
	NEIGHBORHOOD PlaceType = "neighborhood"
	CITY PlaceType = "city"
	ADMIN PlaceType = "admin"
	COUNTRY PlaceType = "country"
	UNKNOWN PlaceType = "unknown"
)
