/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// UrlImage Represent the information for the URL image
type UrlImage struct {
	// A validly formatted URL.
	Url string `json:"url,omitempty"`
	// The height of the media in pixels
	Height int32 `json:"height,omitempty"`
	// The width of the media in pixels
	Width int32 `json:"width,omitempty"`
}
