/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// GenericProblemAllOf struct for GenericProblemAllOf
type GenericProblemAllOf struct {
	Type string `json:"type,omitempty"`
	Status int32 `json:"status"`
}
