/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// StreamingTweetOneOf struct for StreamingTweetOneOf
type StreamingTweetOneOf struct {
	Errors []Problem `json:"errors"`
}
