/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// ConnectionExceptionProblemAllOf struct for ConnectionExceptionProblemAllOf
type ConnectionExceptionProblemAllOf struct {
	Type string `json:"type,omitempty"`
	ConnectionIssue string `json:"connection_issue,omitempty"`
}
