/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	Data InlineResponse200Data `json:"data,omitempty"`
}
