/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// VideoAllOfOrganicMetrics Organic nonpublic engagement metrics for the Media at the time of the request.
type VideoAllOfOrganicMetrics struct {
	// Number of users who made it through 0% of the video.
	Playback0Count int32 `json:"playback_0_count,omitempty"`
	// Number of users who made it through 25% of the video.
	Playback25Count int32 `json:"playback_25_count,omitempty"`
	// Number of users who made it through 50% of the video.
	Playback50Count int32 `json:"playback_50_count,omitempty"`
	// Number of users who made it through 75% of the video.
	Playback75Count int32 `json:"playback_75_count,omitempty"`
	// Number of users who made it through 100% of the video.
	Playback100Count int32 `json:"playback_100_count,omitempty"`
	// Number of times this video has been viewed.
	ViewCount int32 `json:"view_count,omitempty"`
}
