/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// FilteredStreamingTweetOneOfMatchingRules struct for FilteredStreamingTweetOneOfMatchingRules
type FilteredStreamingTweetOneOfMatchingRules struct {
	// Unique identifier of this rule.
	Id string `json:"id"`
	// The user-supplied tag assigned to the rule which matched
	Tag string `json:"tag,omitempty"`
}
