/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// ClientForbiddenProblemAllOf struct for ClientForbiddenProblemAllOf
type ClientForbiddenProblemAllOf struct {
	Type string `json:"type,omitempty"`
	Reason string `json:"reason,omitempty"`
	RegistrationUrl string `json:"registration_url,omitempty"`
}
