/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// UrlFields Represent the portion of text recognized as a URL.
type UrlFields struct {
	// A validly formatted URL.
	Url string `json:"url"`
	// A validly formatted URL.
	ExpandedUrl string `json:"expanded_url,omitempty"`
	// The URL as displayed in the Twitter client.
	DisplayUrl string `json:"display_url,omitempty"`
	// Fully resolved url
	UnwoundUrl string `json:"unwound_url,omitempty"`
	// HTTP Status Code.
	Status int32 `json:"status,omitempty"`
	// Title of the page the URL points to.
	Title string `json:"title,omitempty"`
	// Description of the URL landing page.
	Description string `json:"description,omitempty"`
	Images []UrlImage `json:"images,omitempty"`
}
