/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// VideoAllOf struct for VideoAllOf
type VideoAllOf struct {
	Type string `json:"type,omitempty"`
	PreviewImageUrl string `json:"preview_image_url,omitempty"`
	DurationMs int32 `json:"duration_ms,omitempty"`
	PublicMetrics VideoAllOfPublicMetrics `json:"public_metrics,omitempty"`
	NonPublicMetrics VideoAllOfNonPublicMetrics `json:"non_public_metrics,omitempty"`
	OrganicMetrics VideoAllOfOrganicMetrics `json:"organic_metrics,omitempty"`
	PromotedMetrics VideoAllOfPromotedMetrics `json:"promoted_metrics,omitempty"`
}
