/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// InvalidRequestProblemAllOf struct for InvalidRequestProblemAllOf
type InvalidRequestProblemAllOf struct {
	Type string `json:"type,omitempty"`
	Errors []InvalidRequestProblemAllOfErrors `json:"errors,omitempty"`
}
