/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// AnimatedGifAllOf struct for AnimatedGifAllOf
type AnimatedGifAllOf struct {
	Type string `json:"type,omitempty"`
	PreviewImageUrl string `json:"preview_image_url,omitempty"`
}
