/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// AddOrDeleteRulesRequest struct for AddOrDeleteRulesRequest
type AddOrDeleteRulesRequest struct {
	Add []RuleNoId `json:"add"`
	Ids []string `json:"ids,omitempty"`
	Values []string `json:"values,omitempty"`
}
