/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// VideoAllOfPublicMetrics Engagement metrics for the Media at the time of the request.
type VideoAllOfPublicMetrics struct {
	// Number of times this video has been viewed.
	ViewCount int32 `json:"view_count,omitempty"`
}
