/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// ContextAnnotation Annotation inferred from the tweet text.
type ContextAnnotation struct {
	Domain ContextAnnotationDomainFields `json:"domain"`
	Entity ContextAnnotationEntityFields `json:"entity"`
}
