/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// MentionFields Represent the portion of text recognized as a User mention, and its start and end position within the text.
type MentionFields struct {
	// The Twitter handle (screen name) of this user.
	Username string `json:"username"`
}
