/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// ContextAnnotationEntityFields Represents the data for the context annotation entity.
type ContextAnnotationEntityFields struct {
	// The unique id for a context annotation entity.
	Id string `json:"id"`
	// Name of the context annotation entity.
	Name string `json:"name,omitempty"`
	// Description of the context annotation entity.
	Description string `json:"description,omitempty"`
}
