/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// TweetSearchResponse struct for TweetSearchResponse
type TweetSearchResponse struct {
	Data []Tweet `json:"data,omitempty"`
	Includes Expansions `json:"includes,omitempty"`
	Errors []Problem `json:"errors,omitempty"`
	Meta InlineResponse2001Meta `json:"meta,omitempty"`
}
