/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// TweetAttachments Specifies the type of attachments (if any) present in this Tweet.
type TweetAttachments struct {
	// A list of Media Keys for each one of the media attachments (if media are attached).
	MediaKeys []string `json:"media_keys,omitempty"`
	// A list of poll IDs (if polls are attached).
	PollIds []string `json:"poll_ids,omitempty"`
}
