/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// UserEntities A list of metadata found in the user's profile description.
type UserEntities struct {
	Url UserEntitiesUrl `json:"url,omitempty"`
	Description FullTextEntities `json:"description,omitempty"`
}
