/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// RulesRequestSummary struct for RulesRequestSummary
type RulesRequestSummary struct {
	Created int32 `json:"created"`
	NotCreated int32 `json:"not_created"`
	Deleted int32 `json:"deleted"`
	NotDeleted int32 `json:"not_deleted"`
}
