/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// FieldUnauthorizedProblem A problem that indicates that you are not allowed to see a particular field on a Tweet, User, etc.
type FieldUnauthorizedProblem struct {
	Title string `json:"title"`
	Detail string `json:"detail"`
	Type string `json:"type,omitempty"`
	Section string `json:"section"`
	ResourceType string `json:"resource_type"`
	Field string `json:"field"`
}
