/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// AddOrDeleteRulesResponse struct for AddOrDeleteRulesResponse
type AddOrDeleteRulesResponse struct {
	Data []Rule `json:"data"`
	Meta RulesResponseMetadata `json:"meta"`
}
