/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// ReplySettings Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, and following.
type ReplySettings string

// List of ReplySettings
const (
	EVERYONE ReplySettings = "everyone"
	MENTIONED_USERS ReplySettings = "mentionedUsers"
	FOLLOWING ReplySettings = "following"
	OTHER ReplySettings = "other"
)
