/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// TweetWithheld Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
type TweetWithheld struct {
	// Indicates if the content is being withheld for on the basis of copyright infringement.
	Copyright bool `json:"copyright"`
	// Provides a list of countries where this content is not available.
	CountryCodes []string `json:"country_codes"`
	// Indicates whether the content being withheld is the `tweet` or a `user`.
	Scope string `json:"scope,omitempty"`
}
