/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// UserEntitiesUrl Expanded details for the URL specified in the user's profile, with start and end indices.
type UserEntitiesUrl struct {
	Urls []UrlEntity `json:"urls,omitempty"`
}
