/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// TweetPromotedMetrics Promoted nonpublic engagement metrics for the Tweet at the time of the request.
type TweetPromotedMetrics struct {
	// Number of times this Tweet has been viewed.
	ImpressionCount int32 `json:"impression_count,omitempty"`
	// Number of times this Tweet has been liked.
	LikeCount int32 `json:"like_count,omitempty"`
	// Number of times this Tweet has been replied to.
	ReplyCount int32 `json:"reply_count,omitempty"`
	// Number of times this Tweet has been Retweeted.
	RetweetCount int32 `json:"retweet_count,omitempty"`
}
