/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// RulesRequestSummaryOneOf1 struct for RulesRequestSummaryOneOf1
type RulesRequestSummaryOneOf1 struct {
	Deleted int32 `json:"deleted"`
	NotDeleted int32 `json:"not_deleted"`
}
