/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// FilteredStreamingTweetOneOf The values returned with a successful streamed tweet. Includes the user provided rules that the tweet matched.
type FilteredStreamingTweetOneOf struct {
	Data Tweet `json:"data"`
	// The list of rules which matched the tweet
	MatchingRules []FilteredStreamingTweetOneOfMatchingRules `json:"matching_rules"`
	Includes Expansions `json:"includes,omitempty"`
}
