/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	Data []Rule `json:"data"`
	Meta RulesResponseMetadata `json:"meta"`
}
