/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// Video struct for Video
type Video struct {
	// The Media Key identifier for this attachment.
	MediaKey string `json:"media_key,omitempty"`
	// The height of the media in pixels
	Height int32 `json:"height,omitempty"`
	// The width of the media in pixels
	Width int32 `json:"width,omitempty"`
	Type string `json:"type,omitempty"`
	PreviewImageUrl string `json:"preview_image_url,omitempty"`
	DurationMs int32 `json:"duration_ms,omitempty"`
	PublicMetrics VideoAllOfPublicMetrics `json:"public_metrics,omitempty"`
	NonPublicMetrics VideoAllOfNonPublicMetrics `json:"non_public_metrics,omitempty"`
	OrganicMetrics VideoAllOfOrganicMetrics `json:"organic_metrics,omitempty"`
	PromotedMetrics VideoAllOfPromotedMetrics `json:"promoted_metrics,omitempty"`
}
