/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// RulesRequestSummaryOneOf struct for RulesRequestSummaryOneOf
type RulesRequestSummaryOneOf struct {
	Created int32 `json:"created"`
	NotCreated int32 `json:"not_created"`
}
