/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// CashtagFields Represent the portion of text recognized as a Cashtag, and its start and end position within the text.
type CashtagFields struct {
	Tag string `json:"tag"`
}
