/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// RuleNoId struct for RuleNoId
type RuleNoId struct {
	// The filterlang value of the rule.
	Value string `json:"value"`
	// A tag meant for the labeling of user provided rules.
	Tag string `json:"tag,omitempty"`
}
