/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// TweetOrganicMetrics Organic nonpublic engagement metrics for the Tweet at the time of the request.
type TweetOrganicMetrics struct {
	// Number of times this Tweet has been viewed.
	ImpressionCount int32 `json:"impression_count"`
	// Number of times this Tweet has been Retweeted.
	RetweetCount int32 `json:"retweet_count"`
	// Number of times this Tweet has been replied to.
	ReplyCount int32 `json:"reply_count"`
	// Number of times this Tweet has been liked.
	LikeCount int32 `json:"like_count"`
}
