/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi

// DeleteRulesRequest struct for DeleteRulesRequest
type DeleteRulesRequest struct {
	Delete []RuleDeleteIds `json:"delete"`
}
