/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// PollOption Describes a choice in a Poll object.
type PollOption struct {
	// Position of this choice in the poll.
	Position int32 `json:"position"`
	// The text of a poll choice.
	Label string `json:"label"`
	// Number of users who voted for this choice.
	Votes int32 `json:"votes"`
}
