/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// TweetNonPublicMetrics Nonpublic engagement metrics for the Tweet at the time of the request.
type TweetNonPublicMetrics struct {
	// Number of times this Tweet has been viewed.
	ImpressionCount int32 `json:"impression_count,omitempty"`
}
