/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitclient
// InlineObject struct for InlineObject
type InlineObject struct {
	Hidden bool `json:"hidden,omitempty"`
}
