/*
 * Early Access
 *
 * API Reference — v2
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twitapi
// HashtagFields Represent the portion of text recognized as a Hashtag, and its start and end position within the text.
type HashtagFields struct {
	// The text of the Hashtag
	Tag string `json:"tag"`
}
